function write_coe(h, width, filename)
arguments
    h double
    width double
    filename string = 'untitiled.coe'
end

fd = fopen(filename,'w');  %#ok<MFAMB>
str_date = char(datetime);

str_width = sprintf('%d', width);
str_number = sprintf(['%1.', str_width, 'f'], h(1));

fprintf(fd, "; XILINX CORE Generator(tm)Distributed Arithmetic FIR filter coefficient (.COE) File\n");
fprintf(fd, "; Generated by MATLAB(R) 9.13 and DSP System Toolbox 9.15.\n");
fprintf(fd, ['; Generated on: ', str_date, '\n']);
fprintf(fd, "Radix = 10; \n");
fprintf(fd, "Coefficient_Width = %d; \n", width);
fprintf(fd, ['CoefData =   ', str_number, ',\n']);

for i = 2:length(h)-1
    str_number = sprintf(['%1.', str_width, 'f'], h(i));
    fprintf(fd, ['   ', str_number, ',\n']);
end

str_number = sprintf(['%1.', str_width, 'f'], h(end));
fprintf(fd, ['   ', str_number, ';\n']);
fclose(fd);
end

